### ISSUE TITLE
Issue with the example

### ISSUE THREAD

**Issue by sloppycoffee** [namaggarwal/flask-splitwise-example#1]
The current state of the repo produces this error:

 File "/usr/local/lib/python3.4/dist-packages/splitwise/**init**.py", line 64, in getAuthorizeURL
    return "%s?oauth_token=%s" % (Splitwise.AUTHORIZE_URL, request_token['oauth_token']), request_token['oauth_token_secret']
KeyError: 'oauth_token'

I think it might be an issue with the splitwise package. Would you mind confirming the current state of the repo is working.

**Comment by namaggarwal** [comment]
It looks like the keys you provided have some issue as the response from the Splitwise does not contain oauth_token in the return_url. I will try to return a better error message in this case.

**Comment by sloppycoffee** [comment]
Hmm.. This is what was defined on splitwise registration page.

Homepage URL (required)

http://localhost:5000
Callback URL  Part of the OAuth authentication protocol. When a user approves access to your application, they will be redirected to this URL. (Leave blank for out-of-band authentication.) 

http://localhost:5000/authorize

**Comment by namaggarwal** [comment]
I am able to replicate the issue. It was with the content decoding in the splitwise sdk. It is weird that it works in python 3.3 and 3.5 but not in 3.4. 

Anyways I am closing this issue here and will open an issue in Splitwise SDK repo

**Comment by sloppycoffee** [comment]
So the workaround is to use Python 3.5?

**Comment by namaggarwal** [comment]
No. I am fixing the encoding issues in Splitwise SDK. You should have a new version in some time.

**Comment by sloppycoffee** [comment]
Excellent thanks for all the hard work and debugging.

**Comment by namaggarwal** [comment]
Just released the latest version 0.0.3 with fixes. You can uninstall the previous version and install the latest and run.

**Comment by sloppycoffee** [comment]
Did a pip upgrade on the splitwise package, and then everything went smooth from there! Great work! Thanks!

**Comment by namaggarwal** [comment]
Cool. Thanks for confirming
